<p style="font-size:15pt; text-align:center">
    Introduction to Data Science
</p>
<p style="font-size:20pt; text-align:center">
    Simulation
</p>

In [1]:
import numpy as np
import pandas as pd
import random

# Simulation

If you fix the seed, the number series generated from `random.random` will be the same:

In [2]:
random.seed(10)
print(random.random())
print(random.random())
print(random.random())

random.seed(10)
print(random.random())
print(random.random())
print(random.random())

0.5714025946899135
0.4288890546751146
0.5780913011344704
0.5714025946899135
0.4288890546751146
0.5780913011344704


## Top-down Raquetball simulation

To develop during class

***functions***

printIntro
getInputs

***main:***
* Print an introduction
* Get the inputs: probA, probB, n
* Simulate n games of raquetball using probA and probB
* Output: Print a report on the wins for playerA and playerB

The procedure diagram is:
        <img src="./files/topdown_raquetball.png" width=800px>


In [3]:
# https://github.com/danyoungmusic93/zelle-python/blob/master/chap09/rball.py

# Imports
from random import random


# Functions
def printIntro():
    """Prints the introduction"""
    print("This program simulates a game of racquetball between two")
    print('players called "A" and "B". The abilitites of each player is')
    print("indicated by a probability (a number between 0 and 1) that")
    print("reflects the likelihood of a player winning the serve.")
    print("Player A has the first serve.")

def getInputs():
    """Returns the three simulation parameters"""
    a = eval(input("What is the prob. player A wins a serve? "))
    b = eval(input("What is the prob. player B wins a serve? "))
    n = eval(input("How many games to simulate? "))
    return a, b, n

def simNGames(n, probA, probB):
    """Simulates n games of racquetball between players whose
    abilities are represented by the probability of winning a serve.
    Returns number of wins for A and B
    """
    winsA = winsB = 0
    for i in range(n):
        scoreA, scoreB = simOneGame(probA, probB)
        if scoreA > scoreB:
            winsA = winsA + 1
        else:
            winsB = winsB + 1
    return winsA, winsB

def simOneGame(probA, probB):
    """Simulates a single game of racquetball between players whose
    abilities are represented by the probability of winning a serveself.
    Returns final scores for A and B
    """
    serving = "A"
    scoreA = 0
    scoreB = 0
    while not gameOver(scoreA, scoreB):
        if serving == "A":
            if random() < probA:
                scoreA = scoreA + 1
            else:
                serving = "B"
        elif serving == "B":
            if random() < probB:
                scoreB = scoreB + 1
            else:
                serving = "A"
    return scoreA, scoreB

def gameOver(a, b):
    """a and b represent scores for a racquetball game
    Returns True if the game is over, False otherwise
    """
    return a==15 or b==15

def printSummary(winsA, winsB, n):
    """Prints a summary of wins for each players"""
    print("\nGames simulated: ", n)
    print("Wins for A: {0} ({1:0.1%})".format(winsA, winsA/n))
    print("Wins for B: {0} ({1:0.1%})".format(winsB, winsB/n))


# Main
printIntro()
probA, probB, n = getInputs()
winsA, winsB = simNGames(n, probA, probB)
printSummary(winsA, winsB, n)

This program simulates a game of racquetball between two
players called "A" and "B". The abilitites of each player is
indicated by a probability (a number between 0 and 1) that
reflects the likelihood of a player winning the serve.
Player A has the first serve.
What is the prob. player A wins a serve? .5
What is the prob. player B wins a serve? .4
How many games to simulate? 10

Games simulated:  10
Wins for A: 8 (80.0%)
Wins for B: 2 (20.0%)


### Exploratory unit testing

In [4]:
print(gameOver(0,0))
print(gameOver(5,10))
print(gameOver(15,3))
print(gameOver(3,15))

False
False
True
True


In [5]:
print(simOneGame(.5,.5))
print(simOneGame(.5,.5))
print(simOneGame(.3,.3))
print(simOneGame(.3,.3))
print(simOneGame(.4,.9))
print(simOneGame(.4,.9))
print(simOneGame(.9,.4))
print(simOneGame(.9,.4))
print(simOneGame(.4,.6))
print(simOneGame(.4,.6))

(15, 13)
(13, 15)
(13, 15)
(9, 15)
(2, 15)
(1, 15)
(15, 1)
(15, 0)
(10, 15)
(4, 15)


### Prototyping

In [6]:
from random import random

def simOneGame(): 
    scoreA = 0
    scoreB = 0
    serving = "A"
    for i in range(30):
        if serving == "A":
            if random() < .5:
                scoreA = scoreA + 1 
            else:
                serving = "B"
        else:
            if random() < .5:
                scoreB = scoreB + 1
            else:
                serving = "A"
    print(scoreA, scoreB)
    
    
# main program
simOneGame()

5 11


### Exploratory unit testing of circle_area

In [ ]:
from math import pi

def circle_area(r):
    return pi*(r**2)

# Test function
radii  = [2, 0, -3, 2+5j, True, "radius"]
message = "Area of circles with r = {radius} is {area}."

for r in radii:
    A = circle_area(r)
    print(message.format(radius=r, area=A))

# Code Optimization

Correct order of steps when writing a program:
1. **Make it work**: Write the code in a simple legible way.
2. **Make it right**: Write test cases, make really sure that your algorithm is right and that if you break it.
3. **Make it fast**: Optimize the code by profiling simple use-cases to find the bottlenecks and speeding up these bottlenecks, finding a better algorithm or implementation.

## an example

Fast inverse square root 

3D-games and simulators need billions of real-time inverse square root $\frac{1}{\sqrt{x}}$ calculations for lighting and shading:
<table><tr>
<td> <img src="files/openarena.jpg" width=300px> </td>
<td> <img src="files/surfacenormal.png" width=300px> </td>
</tr></table>

Instead of doing `(float)(1.0/sqrt(x))`, this C++ code was developed in the 1980s/1990s (original comments):

```c++
float Q_rsqrt( float number )
{
	long i;
	float x2, y;
	const float threehalfs = 1.5F;

	x2 = number * 0.5F;
	y  = number;
	i  = * ( long * ) &y;                       // evil floating point bit level hacking
	i  = 0x5f3759df - ( i >> 1 );               // what the fuck? 
	y  = * ( float * ) &i;
	y  = y * ( threehalfs - ( x2 * y * y ) );   // 1st iteration
//	y  = y * ( threehalfs - ( x2 * y * y ) );   // 2nd iteration, this can be removed

	return y;
}
```

It avoids division and is 4 times faster. This is a significant speed-up for millions of real-time calculations every second.
More details: 
https://en.wikipedia.org/wiki/Fast_inverse_square_root

https://betterexplained.com/articles/understanding-quakes-fast-inverse-square-root/

Warning - advanced math: http://www.lomont.org/papers/2003/InvSqrt.pdf

## There is a natural order of making code fast
1. Cheat: Use sample data, solve a simpler problem, buy more RAM, etc.
2. **Profile**: Find out the bottlenecks
3. **Use better algorithms and data structures**
4. Using compiled code written in another language
5. Converting Python code to compiled code
6. Parallelize programs / execute in parallel

## Profiling and timing code

### Magic commands for Jupyter

* `%time`: Time the execution of a single statement
* `%timeit`: Time repeated execution of a single statement for more accuracy
* `%prun`: Run code with the profiler
* `%lprun`: Run code with the line-by-line profiler
* `%memit`: Measure the memory use of a single statement
* `%mprun`: Run code with the line-by-line memory profiler

The last 3 commands are not bundled with Jupyter – you'll need to get the `line_profiler` and `memory_profiler` extension.

In [ ]:
%timeit sum(range(100))

In [ ]:
import random
L = [random.random() for i in range(100000)]
print("sorting an unsorted list:")
%time L.sort()

## Profiling and Optimizing: Monte Carlo method example

We get the value of pi by taking the ratio of area of circle to area of the square, 
where we approximate the area with generated random points, $\frac{\mathrm{area\, of\, circle}}{\mathrm{area\, of\, square}} \approx \frac{\mathrm{points\, in\, circle}}{\mathrm{points\, in\, square}}$
<table><tr>
<td> <img src="files/montecarlo01.png" width=400px></td>
<td> <img src="files/montecarlo02.png" width=400px></td>
</tr></table>

In [11]:
from random import random

def estimate_pi(n = 50000000):
    """Estimate pi with monte carlo simulation."""
    in_circle = 0
    total = n
    
    while n != 0:
        prec_x = random()
        prec_y = random()
        if pow(prec_x, 2) + pow(prec_y, 2) <= 1: # circle equation: x^2+y^2=r^2
            in_circle += 1 # inside the circle
        n -= 1
        
    return 4 * in_circle / total

In [10]:
%time estimate_pi()

CPU times: user 2.96 s, sys: 7.09 ms, total: 2.97 s
Wall time: 2.96 s


3.1424344

From now on, lets normalize this and run `%timeit` always with the same parameters:

In [ ]:
%timeit -r 2 -n 5 estimate_pi()

## Optimization

```python
def estimate_pi(n = 10000000):
    in_circle = 0
    total = n
    
    while n != 0:
        prec_x = random()
        prec_y = random()
        if pow(prec_x, 2) + pow(prec_y, 2) <= 1: # circle equation: x^2+y^2=r^2
            in_circle += 1 # inside the circle
        n -= 1
        
    return 4 * in_circle / total
```

### Algorithmic optimization
Our code is easy to read, but slow, because of:
* while loop
* function calls: pow()

We can replace the whole function with one line!:

In [12]:
def estimate_pi_oneliner(n=1e7):
    return 4 * sum(1 for _ in range(int(n)) if random()**2 + random()**2 <= 1) / n

In [13]:
%timeit -r 2 -n 5 estimate_pi_oneliner()

2.1 s ± 38.2 ms per loop (mean ± std. dev. of 2 runs, 5 loops each)


**What did we do?**
* <span style="color:green">Replace `pow()` with `**`</span>
* <span style="color:green">Replace `while` with `sum(.. for .. in range(n))`</span>
* <span style="color:red">Made the function really hard to read for humans</span>

This is a **generator expression**: `sum(.. for .. in range(n))`



Iterables: Everything that you can use in a for loop. For example:

In [14]:
mylist = [0, 1, 4]
for i in mylist:
    print(i)

0
1
4


In [15]:
mylist = [x*x for x in range(3)]
for i in mylist:
    print(i)

0
1
4


Generators are iterators, but *you can only iterate over them once*. It’s because they do not store all the values in memory, they generate the values on the fly:

In [16]:
mygenerator = (x*x for x in range(3))
for i in mygenerator:
    print(i)

0
1
4


In [17]:
for i in mygenerator:
    print(i)
# Nothing happens

Generators are useful if you run into memory issues.

### Optimization through vectorization

All our operations are still inside the "loop":
```python
sum(1 for _ in range(int(n)) if random()**2 + random()**2 <= 1)
```
    
So we are calling `random()` 2*n times, and we call `if` n times. Do we really need to?

Vectorized version, using numpy:

In [ ]:
import numpy as np

def estimate_pi_vectorized(n=10000000):
    xy = np.random.rand(n, 2)
    inside = np.sum(xy[:, 0]**2 + xy[:, 1]**2 <= 1)
    return 4 * inside / n

In [ ]:
%timeit -r 2 -n 5 estimate_pi_vectorized()

##  effective optimization techniques

### Use better algorithms and data structures, avoid loops

***Example: Unique common elements***

Suppose you were given two lists `xs` and `ys` and asked to find the unique elements in common between them.

In [19]:
xs = np.random.randint(0, 1000, 10000)
ys = np.random.randint(0, 1000, 10000)

In [20]:
# This is easy to solve using a nested loop

def common1(xs, ys):
    """Using lists."""
    zs = []
    for x in xs:
        for y in ys:
            if x==y and x not in zs:
                zs.append(x)
    return zs

%timeit -n1 -r1 common1(xs, ys)

6.38 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [21]:
# However, it is much more efficient to use the set data structure, avoiding loops

def common2(xs, ys):
    return list(set(xs) & set(ys))

%timeit -n1 -r1 common2(xs, ys)

5.14 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


### Avoid function calls and dot notation

***Example: Looped function calls***

In the following example, the function `inner` is called for each element in the list. The overhead of the function call and the argument checking is multiplied 100000 times.

In [ ]:
x = 0
def inner(i):
    global x
    x = x + i
    
def outer1():
    for i in range(100000): 
        inner(i)
        
%timeit outer1()

Here instead, the loop is moved inside the aggregate function so that the function is only called once instead of 100000 times:

In [ ]:
x = 0
def aggregate(list):
    global x
    for i in list:
        x = x + i

def outer2():
    aggregate(range(100000))
    
%timeit outer2()

## Use compiled code

### Cython
http://docs.cython.org/en/latest/src/tutorial/cython_tutorial.html

Cython is Python with C data types.

Cython is Python: Almost any piece of Python code is also valid Cython code. The Cython compiler will convert it into C code which makes equivalent calls to the Python/C API.

### Pypy
https://pypy.org/

Alternative implementaiton of Cython using a just-in-time compiler instead of an interpreter, often making it run faster.

### Numba
https://numba.pydata.org/

Numba is an open source JIT compiler that translates a subset of Python and NumPy code into fast machine code.

## Optimizing code usually comes at the cost of code readability and maintainability!
Think twice if you really need to sacrifice it.

# The End 

**Source**

This notebook was adapted from:
* Data 8: The Foundations of Data Science
* Introduction to Data Science by Michael Szell
* https://towardsdatascience.com/speed-up-jupyter-notebooks-20716cbe2025
* https://jakevdp.github.io/PythonDataScienceHandbook/01.07-timing-and-profiling.html
* https://people.duke.edu/~ccc14/sta-663/MakingCodeFast.html
* Zelle: Python Programming, Chapter 9

In [3]:
import numpy.linalg as nl

In [19]:
a = np.array([[10,100,5],[10,0,105],[110,0,0]])
b = np.array([[15]*3]).T
p = np.array([100.2,93,110])

In [20]:
x = nl.solve(a,b)
x

array([[0.13636364],
       [0.12987013],
       [0.12987013]])

In [16]:
sum(x)

array([0.3961039])

In [14]:
x/sum(x)

array([[0.32786885],
       [0.32786885],
       [0.3442623 ]])

In [21]:
p@x

array([40.02727273])