In [6]:
import numpy as np
import math as mh

In [4]:
A = np.matrix([[8,9],[6,4]])

In [5]:
A

matrix([[8, 9],
        [6, 4]])

In [7]:
np.linalg.svd(A)

(matrix([[-0.86148589, -0.50778151],
         [-0.50778151,  0.86148589]]),
 array([13.94674579,  1.57742891]),
 matrix([[-0.71260897, -0.70156144],
         [ 0.70156144, -0.71260897]]))